apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: eshop-productservice
      context: eshop-productservice
      docker:
        buildArgs:
          HTTP_PROXY: http://70.10.15.10:8080
          HTTPS_PROXY: http://70.10.15.10:8080
    - image: eshop-cartservice
      context: eshop-cartservice
      jib: {}
    - image: eshop-backend
      context: eshop-backend
      jib: {}
    - image: eshop-frontend
      context: eshop-frontend
      docker:
        buildArgs:
          HTTP_PROXY: http://70.10.15.10:8080
          HTTPS_PROXY: http://70.10.15.10:8080
          VUE_APP_BASE_URL: http://localhost/api
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml